# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "wChat"

[default.build.parameters]
cached = true
parallel = true
use_container = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "wChat"
region = "us-east-2"
parameter_overrides = "ExampleApiKey=\"123456789012345678901234567890\" ENV=\"dev\" SESDomain=\"zachariahhansen.com\" SESRegion=\"us-east-2\" SESSenderEmail=\"noreply@zachariahhansen.com\" SESConfigurationSet=\"WorkChatEmailConfig\" FlutterAppUrl=\"https://zachariahhansen.com/\""
image_repositories = []


[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
